# OIL-SIF AI Brain - Domain Lexicon
# All Safety Knowledge used by the AI Engine

LSR_RULES = {
    "Energy Isolation": {
        "icon": "⚡",
        "keywords": ["energy", "isolation", "isolat", "lockout", "lock out", "tagout", "tag out", "loto",
                     "zero energy", "stored", "pressure", "compress", "de-energ", "deenergiz", "purge", "bleed",
                     "vent", "flange", "line break", "line breaking", "opening the line", "open the line",
                     "blanking", "blinding", "residual", "pressurized", "decompression", "hydrostatic",
                     "de-isolation", "disconnect", "disconnected", "energized", "live line", "relief valve",
                     "accumulator", "hydraulic"],
        "controls": ["Identify energy sources", "Isolate", "Lock & tag", "Verify zero energy", "Check residual energy"],
    },
    "Hot Work": {
        "icon": "🔥",
        "keywords": ["hot work", "welding", "weld", "grinding", "grind", "cutt", "torch", "flame", "spark",
                     "brazing", "soldering", "gas cutting", "arc", "burn", "fire watch", "firewatch",
                     "ignition", "combustible", "thermit", "plasma", "oxy", "mpw", "haz area",
                     "grinder", "spark", "slag", "burning"],
        "controls": ["Permit to work verified", "Gas test before & during", "Fire watch assigned", "Flammable material removed", "Continuous monitoring"],
    },
    "Confined Space": {
        "icon": "⬛",
        "keywords": ["confined space", "tank entry", "vessel entry", "pit", "manhole", "sump", "enclosed space",
                     "atmosphere", "oxygen", "gas test", "lel", "h2s", "entry permit", "attendant",
                     "rescue plan", "breathing apparatus", "ba set", "coc", "confined", "underground duct",
                     "caisson", "sewer", "digester"],
        "controls": ["Atmosphere tested", "Isolation verified", "Attendant posted", "Rescue plan in place", "Breathing apparatus", "Entry authorization"],
    },
    "Line of Fire": {
        "icon": "🎯",
        "keywords": ["line of fire", "struck by", "struck-by", "suspended load", "under load", "swing zone",
                     "exclusion", "pinch point", "between", "snapback", "tensioned", "whipping", "kickback",
                     "hand placement", "body position", "load path", "dropped object", "falling object",
                     "overhead", "directly under", "walking under", "barricade"],
        "controls": ["Position outside line of fire", "Exclusion zone maintained", "Body positioning", "Secure the load"],
    },
    "Working at Height": {
        "icon": "🪜",
        "keywords": ["height", "fall", "ladder", "scaffold", "scaffolding", "guardrail", "roof", "platform",
                     "elevated", "harness", "anchor", "freefall", "fall arrest", "mewp", "boom", "work at height",
                     "working at height", "stepladder", "edge", "parapet", "double lanyard", "tie off",
                     "unprotected edge", "gantry", "tank top"],
        "controls": ["Use anchored fall protection", "Inspect ladder/scaffold", "Guard rail in place", "Safe access & egress"],
    },
    "Safe Mechanical Lifting": {
        "icon": "🏗️",
        "keywords": ["lifting", "lift", "crane", "sling", "rigging", "load", "hoist", "hook", "shackle",
                     "derrick", "forklift", "mobile crane", "overhead crane", "pick and carry", "tails",
                     "lift plan", "lifting gear", "shackle", "rigger", "banksman", "load chart", "rated capacity",
                     "center of gravity", "tag line", "hand signal"],
        "controls": ["Lift plan & load chart", "Pre-use inspection of gear", "Certified rigger/banksman", "Physical barriers & tag lines"],
    },
    "Work Authorisation": {
        "icon": "📋",
        "keywords": ["permit", "authorisation", "authorization", "authority", "wpt", "ptw", "no permit",
                     "without permit", "work order", "unauthorized work", "ticket", "sanity permit",
                     "job card", "clearance", "isolation certificate"],
        "controls": ["Valid PTW/authorization verified", "Scope & conditions match", "Sign-off by authorized person"],
    },
    "Driving": {
        "icon": "🚗",
        "keywords": ["driving", "driver", "vehicle", "seatbelt", "seat belt", "speed", "fatigue", "journey",
                     "defensive driving", "reversing", "overtake", "night driving", "parking", "convoy",
                     "road", "collision", "accident vehicle", "mobile equipment", "truck", "tanker",
                     "overloading vehicle"],
        "controls": ["Fatigue management", "Seat belt compliance", "Journey plan & check", "Defensive driving"],
    },
    "Bypassing Safety Controls": {
        "icon": "🚫",
        "keywords": ["bypass", "override", "defeat", "jump", "wire", "tamper", "disable", "safety interlock",
                     "interlock", "relief valve blocked", "alarm bypass", "sensor", "jumper", "hazard light off",
                     "defeat of safety", "fitted delete", "remove guard"],
        "controls": ["Never bypass/disable safety devices", "Repair, don't bypass", "Immediate ESD/ISD protection"],
    },
    "General / Housekeeping": {
        "icon": "🧹",
        "keywords": ["housekeeping", "spill", "clutter", "trip hazard", "untidy", "debris", "oil leak",
                     "slippery", "obstruction", "material stacking", "walkway blocked", "storage"],
        "controls": ["Maintain clear walkways", "Immediate spill cleanup", "Orderly storage & stacking"],
    },
}

ACTIVITIES = {
    "Maintenance": {"keywords": ["maintenance", "maintain", "servicing", "service", "repair", "overhaul", "flange",
                                 "compressor", "pump", "valve", "line", "pipeline work", "fitter", "bolt",
                                 "tighten", "replace", "remove", "install", "inspection", "greasing", "lubrication",
                                 "mechanical work", "opening", "strip", "reassembly", "dismantle"]},
    "Hot Work": {"keywords": ["welding", "weld", "grinding", "grind", "cutting", "cut", "torch", "brazing",
                              "soldering", "gas cutting", "arc", "plasma", "hot work"]},
    "Lifting": {"keywords": ["lifting", "lift", "crane", "rigging", "sling", "hoist", "forklift", "handling",
                             "load", "pick and carry", "banksman", "rigger", "trailer", "loading", "unloading"]},
    "Confined Space Entry": {"keywords": ["confined space", "tank entry", "vessel entry", "pit", "manhole", "sump",
                                          "enclosed space", "caisson", "sewer", "entry into tank"]},
    "Drilling": {"keywords": ["drilling", "well servicing", "workover", "rig", "mud", "well", "drill", "BOP",
                              "wellhead", "servicing", "completion", "cementing", "wireline"]},
    "Excavation": {"keywords": ["excavation", "excavator", "trench", "digging", "dig", "foundation", "earthwork",
                                "shoring", "buried", "underground"]},
    "Electrical Work": {"keywords": ["electrical", "electric", "voltage", "panel", "conductor", "cable", "motor",
                                     "energized", "de-energized", "switchboard", "shock", "electrocution",
                                     "terminal", "junction box", "wire"]},
    "Transportation": {"keywords": ["driving", "vehicle", "transport", "truck", "tanker", "mobile equipment",
                                    "journey", "convoy", "road", "driver", "bus", "pickup"]},
    "Storage / Tank Work": {"keywords": ["tank", "storage", "gauging", "dip", "sample", "roof", "float", "dam",
                                         "bund", "dyke", "pipeline", "transfer", "loading arm", "depot"]},
    "Construction": {"keywords": ["construction", "building", "erection", "civil work", "concrete", "formwork",
                                  "scaffold", "site office", "fabrication", "painting"]},
    "Chemical Handling": {"keywords": ["chemical", "acid", "caustic", "solvent", "additive", "h2s", "toxic",
                                       "corrosive", "drum", "dosage", "chlorine", "ammonia"]},
}

HAZARDS = {
    "Stored Pressure": {"keywords": ["pressure", "pressurized", "stored", "decompression", "blowdown", "relief",
                                     "residual pressure", "residual", "accumulator", "hydraulic pressure", "head"]},
    "Hazardous Energy": {"keywords": ["energy", "electrical", "voltage", "live", "energized", "mechanical", "pneumatic",
                                      "hydraulic", "gravity", "stored energy", "thermal", "chemical energy"]},
    "Confined Atmosphere": {"keywords": ["oxygen", "atmosphere", "gas", "h2s", "lel", "toxic", "fume", "vapour",
                                         "vapor", "deficient", "flammable", "methane", "asphyxiation"]},
    "Moving Equipment": {"keywords": ["rotating", "moving", "gear", "belt", "chain", "coupling", "conveyor",
                                      "rotor", "fan", "machine", "nip point", "caught in"]},
    "Suspended / Dropped Loads": {"keywords": ["suspended", "load", "crane", "slung", "overhead", "dropped",
                                               "falling object", "failed sling", "snap"]},
    "Fire / Explosion": {"keywords": ["fire", "explosion", "flammable", "flash", "ignition", "spark", "combustible",
                                      "vapour cloud", "leak", "gas leak"]},
    "Chemical Exposure": {"keywords": ["chemical", "acid", "caustic", "solvent", "corrosive", "toxic", "skin",
                                       "inhalation", "splash", "drum"]},
    "Fall from Height": {"keywords": ["height", "fall", "ladder", "scaffold", "roof", "elevated", "edge",
                                      "platform", "opening"]},
    "Vehicle / Mobile Equipment": {"keywords": ["vehicle", "truck", "tanker", "reversing", "collision", "mobile",
                                                "forklift", "struck by vehicle", "rollover"]},
    "Slip / Trip / Fall": {"keywords": ["slip", "trip", "fall", "slippery", "uneven", "obstruction", "clutter",
                                        "spill", "walkway"]},
    "Electrical Hazard": {"keywords": ["electrical", "volt", "shock", "arc flash", "arc", "cable", "cable damage",
                                       "overhead line", "power line", "electrocution"]},
}

BARRIERS = {
    "Permit Verification": {"keywords": ["permit", "ptw", "no permit", "without permit", "expired permit", "invalid permit",
                                         "work order", "authorization", "wpt"]},
    "Energy Isolation": {"keywords": ["isolation", "isolat", "lockout", "tagout", "loto", "zero energy", "verify",
                                      "verification", "de-energ", "not isolated", "no isolation", "blinding", "blanking"]},
    "Gas Testing": {"keywords": ["gas test", "gas testing", "no gas test", "atmosphere", "tested", "oxygen", "lel",
                                 "monitoring", "calibration", "h2s", "toxic gas"]},
    "Barricading": {"keywords": ["barricade", "barricating", "barricading", "exclusion", "no barricade", "cordon",
                                 "tape", "barrier", "signage", "warning", "guarding"]},
    "PPE Compliance": {"keywords": ["ppe", "helmet", "helment", "goggles", "gloves", "shoe", "boot", "harness",
                                    "no ppe", "glasses", "face shield", "respirator", "ear plug", "ear plug",
                                    "reflective", "overall"]},
    "Supervision": {"keywords": ["supervision", "supervisor", "no supervision", "unsupervised", "inadequate supervision",
                                 "alone", "not attended", "attendant missing"]},
    "Communication / Toolbox": {"keywords": ["toolbox", "tbsta", "briefing", "communication", "handover", "no toolbox",
                                             "pre-job", "prestart", "jha not discussed", "not informed"]},
    "Housekeeping": {"keywords": ["housekeeping", "clutter", "spill", "debris", "untidy", "obstruction", "stacking",
                                  "slippery", "oil on floor"]},
    "Competency / Training": {"keywords": ["untrained", "competency", "not certified", "trainee working alone",
                                          "not qualified", "inexperienced", "no license", "refresher"]},
    "Equipment Condition": {"keywords": ["defective", "damaged", "faulty", "not inspected", "expired", "failed",
                                        "leaking", "corroded", "worn", "broken", "no inspection"]},
}

CONSEQUENCES = {
    "Pressure Release": {"keywords": ["pressure", "blowout", "release", "rupture", "blowdown", "flush", "blow"]},
    "Fatal Injury": {"keywords": ["fatal", "death", "serious injury", "crush", "struck", "fall", "electrocute"]},
    "Fire / Explosion": {"keywords": ["fire", "explosion", "flash fire", "jet fire"]},
    "Crush / Entanglement": {"keywords": ["crush", "caught", "entangle", "pinch", "nip", "body parts", "hand"]},
    "Fall Injury": {"keywords": ["fall", "fell", "slipped", "trip", "height"]},
    "Struck-by Injury": {"keywords": ["struck", "hit", "struck by", "dropped", "thrown"]},
    "Burn Injury": {"keywords": ["burn", "scald", "hot surface", "arc", "flash"]},
    "Asphyxiation / Exposure": {"keywords": ["asphyxia", "oxygen deficient", "toxic gas", "exposure", "inhale",
                                             "vapour", "fume", "h2s"]},
    "Vehicle Collision": {"keywords": ["collision", "reversing", "vehicle", "rollover", "road accident"]},
    "Environmental Spill": {"keywords": ["spill", "leak", "crude", "hydrocarbon", "discharge", "drain"]},
}

ROOT_CAUSES = {
    "Human Factors": ["complacency", "fatigue", "rushed", "shortcut", "habit", "stress", "overconfidence"],
    "Procedure": ["procedure", "sop", "step missing", "not followed", "work instruction", "no procedure"],
    "Training / Competency": ["training", "trained", "competency", "inexperienced", "skill", "new joiner", "transfer"],
    "Supervision": ["supervision", "supervisor", "oversight", "no supervision", "left alone"],
    "Equipment": ["defective", "faulty", "equipment failure", "maintenance", "worn", "aged", "calibration"],
    "Management System": ["management", "system", "audit", "policy", "program", "culture", "workload"],
    "Contractor": ["contractor", "subcontract", "vendor", "agent"],
    "Communication": ["communication", "handover", "miscommunication", "language", "not informed", "toolbox"],
    "Planning": ["planning", "risk assessment", "jha", "scheduling", "job plan", "lookahead"],
    "Environment": ["weather", "rain", "wind", "heat", "visibility", "night", "muddy", "remote"],
}

ACTIVITY_HINTS = {
    "Maintenance": ["flange", "compressor", "pump", "valve", "bolt", "maintenance", "repair", "overhaul", "service"],
    "Hot Work": ["welding", "grind", "torch", "cutting", "brazing", "hot work", "spark"],
    "Lifting": ["crane", "lifting", "sling", "rigging", "hoist", "forklift", "load"],
    "Confined Space Entry": ["confined space", "tank entry", "vessel", "pit", "manhole"],
    "Drilling": ["drilling", "rig", "well", "workover", "wireline", "mud"],
    "Excavation": ["excavation", "excavator", "trench", "digging", "earthwork"],
    "Electrical Work": ["electrical", "electrical work", "voltage", "panel", "cable"],
    "Transportation": ["driving", "vehicle", "transport", "journey", "truck"],
    "Storage / Tank Work": ["tank", "storage", "gauging", "bund", "dyke"],
    "Construction": ["construction", "erection", "civil", "scaffold", "fabrication"],
}

LOCATION_HINTS = {
    "Well Site": ["well", "well site", "wellhead", "rig"],
    "Processing Plant": ["plant", "process", "dp", "gas sweetening", "unit"],
    "Compressor Station": ["compressor", "compress station", "cgt"],
    "Pipeline": ["pipeline", "plc", "cross country", "pig", "right of way"],
    "Workshop": ["workshop", "mechanical workshop", "work shop"],
    "Warehouse": ["warehouse", "stor", "godown", "ware house"],
    "Construction Site": ["construction", "site development", "building"],
    "Tank Farm": ["tank farm", "tank", "tank no", "floating roof"],
    "Drilling Site": ["drilling", "rig site"],
    "Office / Admin": ["office", "admin", "canteen", "guest house"],
}

MULTILANG = {
    "hindi": {
        "कामगार": "worker", "कर्मचारी": "employee", "बिना": "without", "परमिट": "permit",
        "हॉट वर्क": "hot work", "गरम काम": "hot work", "वेल्डिंग": "welding",
        "ग्राइंडिंग": "grinding", "कटिंग": "cutting", "काम": "work",
        "ऊंचाई": "height", "गैस": "gas", "टेस्ट": "test", "जांच": "check",
        "अलगाव": "isolation", "ऊर्जा": "energy", "दबाव": "pressure",
        "लाइन": "line", "फ्लैंज": "flange", "खुला": "open", "खोला": "opened",
        "खतरनाक": "dangerous", "खतरा": "hazard", "बिना हेलमेट": "without helmet",
        "सुरक्षा": "safety", "सीमित स्थान": "confined space", "टंकी": "tank",
        "प्रवेश": "entry", "कार्य": "work", "मशीन": "machine", "अराजक": "unsafe",
        "तार": "wire", "बिजली": "electricity", "आग": "fire", "लिफ्टिंग": "lifting",
        "क्रेन": "crane", "लोड": "load", "गिर": "fall", "हटाना": "remove",
        "चालक": "driver", "गाड़ी": "vehicle", "तेज़": "fast", "रात्रि": "night",
        "अनुमति": "permission", "नहीं": "not", "हुआ": "was", "था": "was",
        "कर": "doing", "रहा": "being", "समर्थन": "support", "परीक्षण": "test",
        "माप": "measure", "ऑक्सीजन": "oxygen", "हाइड्रोजन सल्फाइड": "hydrogen sulfide",
        "निगरानी": "supervision", "अकेला": "alone", "बिना सुपरवाइजर": "without supervisor",
        "सवारी": "riding", "संकेत": "sign", "बैरिकेड": "barricade", "नहीं लगाया": "not placed",
        "उतरना": "descent", "चढ़ना": "climb", "सीढ़ी": "ladder", "मंच": "platform",
    },
    "assamese": {
        "কামী": "worker", "পৰমিট": "permit", "বিনা": "without", "সীমিত স্থান": "confined space",
        "উচ্চতা": "height", "গেছ": "gas", "পৰীক্ষা": "test", "আইছ'লেছন": "isolation",
        "শক্তি": "energy", "চাপ": "pressure", "ফ্লেঞ্চ": "flange", "সৰঞ্জাম": "equipment",
        "কাম": "work", "অসুৰক্ষিত": "unsafe", "নহয়": "not", "বেল্ডিং": "welding",
        "কাটিং": "cutting", "লিফটিং": "lifting", "ক্ৰেন": "crane", "ভাৰ": "load",
    },
    "bengali": {
        "কর্মী": "worker", "পারমিট": "permit", "ছাড়া": "without", "তাপ": "heat",
        "সীমিত স্থান": "confined space", "উচ্চতা": "height", "গ্যাস": "gas",
        "পরীক্ষা": "test", "আইসোলেশন": "isolation", "শক্তি": "energy", "চাপ": "pressure",
        "ফ্ল্যাঞ্জ": "flange", "কাজ": "work", "ঝুঁকি": "hazard", "নিরাপত্তা": "safety",
        "ওয়েল্ডিং": "welding", "গ্রাইন্ডিং": "grinding", "কাটিং": "cutting",
        "লিফটিং": "lifting", "ক্রেন": "crane", "লোড": "load", "পড়ে": "fall",
    },
    "odia": {
        "କର୍ମୀ": "worker", "ପରମିଟ": "permit", "ବିନା": "without", "ସୀମିତ ସ୍ଥାନ": "confined space",
        "ଉଚ୍ଚତା": "height", "ଗ୍ୟାସ": "gas", "ପରୀକ୍ଷା": "test", "ବିଚ୍ଛିନ୍ନତା": "isolation",
        "ଶକ୍ତି": "energy", "ଚାପ": "pressure", "କାମ": "work", "ଅସୁରକ୍ଷିତ": "unsafe",
        "ନାହିଁ": "not", "ଫ୍ଲେଞ୍ଜ": "flange", "ୱେଲ୍ଡିଂ": "welding", "କଟିଂ": "cutting",
        "ଲିଫ୍ଟିଂ": "lifting", "କ୍ରେନ": "crane", "ଲୋଡ": "load",
    },
}

SCRIPT_RANGES = {
    "hindi": (0x0900, 0x097F),       # Devanagari
    "assamese": (0x0900, 0x097F),    # Devanagari (Assamese)
    "bengali": (0x0980, 0x09FF),     # Bengali
    "odia": (0x0B00, 0x0B7F),        # Odia
}